# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-01-15 05:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('likes_books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='book',
            name='uploaded',
        ),
        migrations.AddField(
            model_name='book',
            name='liked_by_users',
            field=models.ManyToManyField(related_name='liked_books', to='likes_books.User'),
        ),
        migrations.AddField(
            model_name='book',
            name='uploader',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_books', to='likes_books.User'),
            preserve_default=False,
        ),
    ]
